version: '3'

volumes:  # Подключаемые тома
  pg_data:  # Для PostgreSQL
  static:  # Для статики
  media:  # Для медиа-файлов (картинки)

services:
  db:
    image: postgres:13
    volumes:
      - pg_data:/var/lib/postgresql/data  # Подключение том для данных БД
    env_file: .env  # Подключение .env для контейнера db
  backend:
    image: marteszibellina/kittygram_backend
    env_file: .env
    volumes:
      - static:/backend_static  # Статика
      - media:/app/media  # Медиа
    depends_on:
      - db

  frontend:
    env_file: .env
    image: marteszibellina/kittygram_frontend
    command: cp -r /app/build/. /static/
    volumes:
      - static:/static
  gateway:
    image: marteszibellina/kittygram_gateway
    env_file: .env
    ports:
      - 9000:80
    volumes:
      - static:/static
      - media:/media
    depends_on:
      - backend
